#import <CoreData/CoreData.h>
#import <rootless.h>
#import "EZPhraseListViewController.h"
#import "EZAddPhraseViewController.h"
#import "EZEditPhraseViewController.h"
static NSString *settingsPath = ROOT_PATH_NS(@"/var/mobile/Library/Preferences/xyz.skitty.ersatz.plist");
@implementation EZPhraseListViewController
- (void)viewDidLoad { [super viewDidLoad]; self.title = @"Ersatz"; self.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemAdd target:self action:@selector(addPhrase)]; self.tableView = [[UITableView alloc] initWithFrame:self.view.bounds style:UITableViewStylePlain]; self.tableView.delegate = self; self.tableView.dataSource = self; [self.view addSubview:self.tableView]; CFArrayRef keys = CFPreferencesCopyKeyList(CFSTR("xyz.skitty.ersatz"), kCFPreferencesCurrentUser, kCFPreferencesAnyHost); if (keys) { _settings = (NSMutableDictionary *)CFBridgingRelease(CFPreferencesCopyMultiple(keys, CFSTR("xyz.skitty.ersatz"), kCFPreferencesCurrentUser, kCFPreferencesAnyHost)); CFRelease(keys); } else _settings = [[NSMutableDictionary alloc] initWithContentsOfFile:settingsPath]; if (!_settings) _settings = [NSMutableDictionary dictionary]; _settings[@"strings"] = [_settings[@"strings"] mutableCopy] ?: [NSMutableArray array]; [self sortSettings]; }
- (void)updateSettings { CFPreferencesSetAppValue(CFSTR("strings"), (__bridge CFPropertyListRef)_settings[@"strings"], CFSTR("xyz.skitty.ersatz")); [_settings writeToFile:settingsPath atomically:YES]; CFNotificationCenterPostNotification(CFNotificationCenterGetDarwinNotifyCenter(), CFSTR("xyz.skitty.ersatz.prefschanged"), NULL, NULL, true); }
- (void)sortSettings { _strings = [NSMutableDictionary dictionary]; _sortedStrings = [NSMutableDictionary dictionary]; for (NSDictionary *r in _settings[@"strings"]) { NSString *p = r[@"phrase"]; if (!p.length) continue; _strings[p] = r[@"replacement"] ?: @""; NSString *s = [[p substringToIndex:1] uppercaseString]; if (!_sortedStrings[s]) _sortedStrings[s] = [NSMutableArray array]; [_sortedStrings[s] addObject:p]; } for (NSString *s in _sortedStrings) [_sortedStrings[s] sortUsingSelector:@selector(localizedCaseInsensitiveCompare:)]; }
- (void)addPhrase { EZAddPhraseViewController *c = [EZAddPhraseViewController new]; c.parent = self; [self.navigationController pushViewController:c animated:YES]; }
- (void)addPhrase:(NSString *)p replacement:(NSString *)r caseSensitive:(BOOL)c wholeWord:(BOOL)w scope:(NSString *)s applications:(NSArray *)a { if (!_settings[@"shownPrompt"]) { UIAlertController *alert = [UIAlertController alertControllerWithTitle:@"Notice" message:@"Changes may require reopening apps or respringing." preferredStyle:UIAlertControllerStyleAlert]; [alert addAction:[UIAlertAction actionWithTitle:@"OK" style:UIAlertActionStyleDefault handler:nil]]; [self presentViewController:alert animated:YES completion:nil]; _settings[@"shownPrompt"] = @YES; } NSMutableDictionary *rule = [@{ @"phrase": p, @"replacement": r, @"caseSensitive": @(c), @"wholeWord": @(w), @"scope": s ?: @"all", @"applications": a ?: @[] } mutableCopy]; [_settings[@"strings"] addObject:rule]; [self updateSettings]; [self sortSettings]; [self.tableView reloadData]; }
- (void)editPhrase:(NSString *)old newPhrase:(NSString *)p replacement:(NSString *)r caseSensitive:(BOOL)c wholeWord:(BOOL)w scope:(NSString *)s applications:(NSArray *)a { for (NSUInteger i=0; i<[_settings[@"strings"] count]; i++) if ([_settings[@"strings"][i][@"phrase"] isEqualToString:old]) { _settings[@"strings"][i] = @{ @"phrase": p, @"replacement": r, @"caseSensitive": @(c), @"wholeWord": @(w), @"scope": s ?: @"all", @"applications": a ?: @[] }; break; } [self updateSettings]; [self sortSettings]; [self.tableView reloadData]; }
- (NSArray *)sections { return [[_sortedStrings allKeys] sortedArrayUsingSelector:@selector(localizedCaseInsensitiveCompare:)]; }
- (NSInteger)numberOfSectionsInTableView:(UITableView *)t { return _sortedStrings.count; }
- (NSInteger)tableView:(UITableView *)t numberOfRowsInSection:(NSInteger)s { return [_sortedStrings[[self sections][s]] count]; }
- (NSString *)tableView:(UITableView *)t titleForHeaderInSection:(NSInteger)s { return [self sections][s]; }
- (UITableViewCell *)tableView:(UITableView *)t cellForRowAtIndexPath:(NSIndexPath *)i { UITableViewCell *c = [t dequeueReusableCellWithIdentifier:@"Cell"] ?: [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleValue1 reuseIdentifier:@"Cell"]; NSString *p = _sortedStrings[[self sections][i.section]][i.row]; c.textLabel.tag=317; c.detailTextLabel.tag=317; c.textLabel.text=p; c.detailTextLabel.text=_strings[p]; return c; }
- (void)tableView:(UITableView *)t didSelectRowAtIndexPath:(NSIndexPath *)i { NSString *p=_sortedStrings[[self sections][i.section]][i.row]; for (NSDictionary *r in _settings[@"strings"]) if ([r[@"phrase"] isEqualToString:p]) { EZEditPhraseViewController *c=[[EZEditPhraseViewController alloc] initWithDictionary:r]; c.parent=self; [self.navigationController pushViewController:c animated:YES]; break; } [t deselectRowAtIndexPath:i animated:YES]; }
- (void)tableView:(UITableView *)t commitEditingStyle:(UITableViewCellEditingStyle)e forRowAtIndexPath:(NSIndexPath *)i { if (e != UITableViewCellEditingStyleDelete) return; NSString *p=_sortedStrings[[self sections][i.section]][i.row]; for (NSDictionary *r in [_settings[@"strings"] copy]) if ([r[@"phrase"] isEqualToString:p]) { [_settings[@"strings"] removeObject:r]; break; } [self updateSettings]; [self sortSettings]; [t reloadData]; }
@end
